### PR TITLE
fix(game): Dropping item

### LINKED ISSUE #167: Dropping an item from inventory causes foreign key constraint violation
````
[ERR]An exception occurred in the database while saving changes for context type 'QuantumCore.Game.Persistence.MySqlGameDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> MySqlConnector.MySqlException (0x80004005): Cannot add or update a child row: a foreign key constraint fails (`metin2`.`Items`, CONSTRAINT `FK_Items_Players_PlayerId` FOREIGN KEY (`PlayerId`) REFERENCES `Players` (`Id`) ON DELETE CASCADE)
   at MySqlConnector.Core.ServerSession.ReceiveReplyAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/ServerSession.cs:line 894
[...]
   --- End of inner exception stack trace ---
[...]
```

### PR DESCRIPTION
**Pull request by MeikelLP**
Don't set db items player ID to 0 but instead remove the item

fixes #167

### CODE REVIEW

File: src/Executables/Game/Extensions/ItemExtensions.cs [hunk 1]
```diff
@@ -121,6 +121,16 @@ public static uint GetMaxMagicWeaponDamage(this ItemData item)
         return item;
     }
 
+    public static async Task DeletePlayerItemAsync(this IItemRepository repository, ICacheManager cacheManager,
+        uint playerId, uint itemId)
+    {
+        var key = "item:" + itemId;
```
Comment (uutkukorkmaz) [inline src/Executables/Game/Extensions/ItemExtensions.cs:127]: I think we should be consistent on how we define redis keys. Please consider apply suggestion
```suggestion
        var key = $"item:{itemId]";
```

Comment (MeikelLP) [reply src/Executables/Game/Extensions/ItemExtensions.cs]: Valid

**Review by uutkukorkmaz — APPROVED** [review]
